version: "3.7"
services:
  openldap:
    container_name: ldap
    image: bitnami/openldap:latest
    environment:
      LDAP_CONFIG_ADMIN_ENABLED: "yes"
    ports:
      - '1389:1389'
      - '1636:1636'

  keycloak-db:
    container_name: keycloak-db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: keycloak

  keycloak:
    container_name: keycloak
    build:
      context: .
      dockerfile: docker.build/keycloak.Dockerfile
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: secret
      KEYCLOAK_ADMIN: keycloak_admin
      KEYCLOAK_ADMIN_PASSWORD: keycloak_secret
    volumes:
      - "./realm/realm.json:/opt/keycloak/data/import/realm.json"
    depends_on:
      - keycloak-db

  pets-db:
    container_name: pets-db
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./docker-entrypoint-initdb.d/db-init.js:/docker-entrypoint-initdb.d/db-init.js:ro

  mongo-viewer:
    container_name: mongo-viewer
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - "5002:8081"
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: pets-db
    depends_on:
      - pets-db

  openldap-ui:
    container_name: ldap-ui
    image: dnknth/ldap-ui
    environment:
      LDAP_URL: "ldap://openldap:1389"
      BASE_DN: dc=example,dc=org
    ports:
      - "5001:5000"
    depends_on:
      - openldap
